tests: Enable optional qemu unit tests for xen platform
This enables qemu unit tests to run on gnumach as xen dom0.
However, it will skip running the tests if xen binary is missing.
Therefore, the test suite will not fail if not intending to test xen.
This is useful, for example on CI where we want to see a pass status
for most of the tests without fully testing xen which is difficult to
execute.

This should make debugging easier for anyone interested in progressing
the xen dom0 port of gnumach.
Message-ID: <20260704035814.109936-2-damien@zamaudio.com>

diff --git a/tests/run-qemu.sh.template b/tests/run-qemu.sh.template
--- a/tests/run-qemu.sh.template
+++ b/tests/run-qemu.sh.template
@@ -21,8 +21,14 @@ cmd="QEMU_BIN QEMU_OPTS -cdrom tests/test-TESTNAME.iso"
 log="tests/test-TESTNAME.raw"
 
 echo "temp log $log"
+
+if PLATFORM_XEN && [ ! -e 'XEN_BIN' ]; then
+    echo "skipping, XEN_BIN not found for xen tests"
+    exit 77
+fi
+
 if which QEMU_BIN >/dev/null ; then
-    if ! timeout -v --foreground --kill-after=3 60s $cmd \
+    if ! timeout -v --foreground --kill-after=3 120s $cmd \
             | tee $log | sed -n "/TEST_START_MARKER/"',$p' ; then
         exit 10  # timeout
     fi
